language: python
os:
  - linux
matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
      sudo: required
      dist: xenial
    - python: nightly
      sudo: required
      dist: xenial
    #power_jobs
    - python: 3.6
      arch: pp64le
    - python: 3.7
      arch: ppc64le
    - python: 3.8
      arch: ppc64le
      sudo: required
      dist: xenial
    - python: nightly
      arch: ppc64le
      sudo: required
      dist: xenial       
  allow_failures:
    - python: nightly
# command to run tests
install: python setup.py develop
script: python setup.py test

